### ISSUE TITLE
2.0.0-RC1 refers to non-existing parent

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/common-annotations-api#73]
* add a dependency on 2.0.0-RC1 api artifact to maven project
* run the maven build

=>
Could not find artifact jakarta.annotation:ca-parent:pom:2.0.0-RC1 in central

**Comment by arjantijms** [comment]
The parent for this version indeed has not been published, see:

https://repo.maven.apache.org/maven2/jakarta/annotation/ca-parent/

(I think it's best anyway not have this parent dependency at all in the published pom for the API)

**Comment by senivam** [comment]
progress on this issue is delayed due to issues with Eclipse's infrastructure. Currently there is a bug [560143](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560143). The purpose of this bug is to allow CA jobs at Eclipse's infrastructure to be run. For now there are no executors allocated for CA JIPP.

**Comment by senivam** [comment]
Fixed, can be closed 
https://repo1.maven.org/maven2/jakarta/annotation/ca-parent/2.0.0-RC1/

**Comment by lukasj** [comment]
yup, works now
